version: "3"

services:
  counterApp_frontend:
    image: node:latest
    container_name: counterApp_frontend
    build: .
    command: ng serve 
    ports: 
      - "4200:4200"
    volumes:
      - .:usr/src/projects/counterApp
